@echo off

set ScriptDir=%~dp0
set TestProjectDir=%ScriptDir%tests
set ProjectInfo=%TestProjectDir%\ProjectInfo.cs

echo Creating source file with project info for tests...
echo   %ProjectInfo%

echo // Generated by %~nx0 > %ProjectInfo%
echo. >> %ProjectInfo%
echo namespace Landis.Test.LandUses >> %ProjectInfo%
echo { >> %ProjectInfo%
echo     public static class ProjectInfo >> %ProjectInfo%
echo     { >> %ProjectInfo%
echo         public static readonly string Directory = @"%TestProjectDir%"; >> %ProjectInfo%
echo     } >> %ProjectInfo%
echo } >> %ProjectInfo%
