with (LANDIS)
{
    addPlugIn("Age-only Succession", "2.0", "succession", "Succession with age cohorts", "LANDIS-II Age-Only Succession v1.2 User Guide.pdf")
    addPlugIn("Base BDA", "1.3", "disturbance:BDA", "Biological disturbance agents", "LANDIS-II Base BDA v1.3 User Guide.pdf")
    addPlugIn("Base Fire", "2.1.1", "disturbance:fire", "Fire Disturbance", "LANDIS-II Base Fire v2.01 User Guide.pdf")
    addPlugIn("Base Harvest", "1.3", "disturbance:harvest", "Harvesting for age cohorts", "LANDIS-II Harvest v1.2 User Guide.pdf")
    addPlugIn("Base Wind", "1.2.2", "disturbance:wind", "Wind Disturbance", "LANDIS-II Base Wind v1.2 User Guide.pdf")
    addPlugIn("Biomass Harvest", "@VER_REL_ABBR@", "disturbance:harvest", "Harvesting for biomass cohorts", "Biomass Harvest @VER_REL_ABBR@ User Guide.html")
    addPlugIn("Biomass Reclass", "1.1", "output", "Output forest reclassification maps using biomass", "LANDIS-II Biomass Reclass Output v1.0 User Guide.pdf")
    addPlugIn("Biomass Succession v2", "2.1.7", "succession", "Succession with biomass cohorts", "LANDIS-II Biomass Succession v2.0 User Guide.pdf")
    addPlugIn("Biomass Succession v3", "1.0", "succession", "Succession with biomass cohorts", "LANDIS-II Biomass Succession v3.0 User Guide.pdf")
    addPlugIn("Century Succession", "1.0", "succession", "Succession with biomass cohorts and Century soil model", "LANDIS-II Century Succession v1.0 User Guide.pdf")
    addPlugIn("Dynamic Biomass Fuels", "1.1", "disturbance:fuel", "Dynamic Fuel assignment extension using Biomass", "")
    addPlugIn("Dynamic Fire System", "1.0", "disturbance:fire", "Dynamic Fire System", "")
    addPlugIn("Dynamic Fuel System", "1.0", "disturbance:fuel", "Dynamic Fuel assignment extension", "")
    addPlugIn("Dynamic Fuels Leaf Biomass", "1.0", "disturbance:fuel", "Dynamic fuel assignment based on Leaf Biomass cohorts", "")
    addPlugIn("Leaf Biomass Harvest", "@VER_REL_ABBR@", "disturbance:harvest", "Harvesting for lef biomass cohorts", "LANDIS-II Leaf Biomass Harvest @VER_REL_ABBR@ User Guide.html")
    addPlugIn("Max Species Age", "1.1", "output", "Maximum age output maps", "LANDIS-II Age Output v1.1 User Guide.pdf")
    addPlugIn("Nutrient Cycling Succession", "1.0", "succession", "Nutrient cycling succession extension.", "")
    addPlugIn("Output Biomass", "1.2.1", "output", "Output biomass maps", "LANDIS-II Biomass Output v1.2 User Guide.pdf")
    addPlugIn("Output Biomass AgeClass", "1.0", "output", "Output biomass by ageclass by species", "")
    addPlugIn("Output Cohort Stats", "1.0", "output", "This extension will produce outputs of cohort statistics", "")
    addPlugIn("Output Leaf Biomass", "1.0", "output", "Output biomass for cohorts with separate leaf and wood biomass", "")
    addPlugIn("Output Reclass", "1.1", "output", "Output forest reclassification maps", "LANDIS-II Reclass Output v1.1 User Guide.pdf")
    addPlugIn("PnET Succession", "1.0", "succession", "PnET Succession", "LANDIS-II PnET Succession v1.0 User Guide.pdf")
}
